### ISSUE TITLE
交易关闭

### ISSUE THREAD

**Issue by bladetin** [312885991/seckill_tools#13]
到点可以提交订单，但是订单由于交易风险，直接交易关闭，这是为什么

**Comment by ak-cxy** [comment]
你好，我想问一下，“Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\seckill_tools-master\main.py", line 5, in <module>
    from seckill.taobao import TaoBao
  File "C:\Users\lenovo\Desktop\seckill_tools-master\seckill\taobao.py", line 5, in <module>
    from selenium import webdriver
ModuleNotFoundError: No module named 'selenium'”
我一在main.py中运行代码就出现这个错误，但是我安装了selenium这个库，怎么解决啊
<img width="1034" alt="屏幕截图 2024-05-03 202323" src="https://github.com/312885991/seckill_tools/assets/150604106/28b7e93d-58c9-4c1a-a7bd-b88cbd8d36cd">
