### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 2013040936zxt** [312885991/seckill_tools#2]
Traceback (most recent call last):
  File "D:\py_lianxi\seckill_tools-master\main.py", line 5, in <module>
    from seckill.taobao import TaoBao
  File "D:\py_lianxi\seckill_tools-master\seckill\taobao.py", line 11, in <module>
    from utils.utils import notify_user
ModuleNotFoundError: No module named 'utils.utils'

**Comment by 312885991** [comment]
看错误就是找不到模块，可是你这信息有限，找百度搜一下解决办法吧，这是非程序问题
